# Używam obrazu pythona
FROM python:latest

# Kopiowanie skryptu do kontenera
COPY password-generator.py /password-generator.py

# Ustawiam skrypt jako punkt wejścia
ENTRYPOINT ["python", "/password-generator.py"]
